name: CI
on:
  push:
    branches: [ live ]
  pull_request:
    branches: [ live ]

  workflow_dispatch:

jobs:
  markdown-lint:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Markdown Linting Action
        uses: avto-dev/markdown-lint@v1.5.0
        with:
          args: './README.md'
