name: Markdown lint
on:
  push:
    paths:
      - "**.md"
      - ".github/workflows/markdown-lint.yml"
  pull_request:
    paths:
      - "**.md"
      - ".github/workflows/markdown-lint.yml"
    branches: [ live ]

  workflow_dispatch:

jobs:
  markdown-lint:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Markdown Linting Action
        uses: avto-dev/markdown-lint@v1.5.0
        with:
          args: './**/*.md'
          config: './.github/markdown-lint-config.yml'
