# This is a basic workflow to help you get started with Actions

name: Print out

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the live branch
  push:
    paths:
      - "**.md"
      - ".github/workflows/print-in-various-format.yml"
    branches: [ live ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: prepare output directory
        run: |
          mkdir output
      - name: set current datetime
        id: datetime
        run: |
          export TZ='Asia/Tokyo'
          CURDATETIME="$(date +%Y%m%d_%H%M%S)"
          echo "::set-output name=dt::$CURDATETIME"
        # TODO: このステップを独立したアクションに分割して依存させる
      - name: Download preprocessor
        env:
          PREPROCESSOR_VERSION: "0.1.2"
        run: |
          ./fetch_preprocessor.sh
      - name: Run preprocessor
        run: |
          ./markdown-template-preprocessor -i ./README.template.md -o ./output/README.md -m static
      - name: Convert into PDF
        uses: docker://pandoc/latex:2.19
        with:
          args: --output=output/README_${{ steps.datetime.outputs.dt }}.pdf output/README.md
      - name: Convert into HTML
        uses: docker://pandoc/latex:2.19
        with:
          args: --output=output/README_${{ steps.datetime.outputs.dt }}.html output/README.md
      - name: Convert into DOCX
        uses: docker://pandoc/latex:2.19
        with:
          args: --output=output/README_${{ steps.datetime.outputs.dt }}.docx output/README.md
      - name: Eliminate intermediate markdown
        run:
          rm output/README.md
      - name: Push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ env.CURDAYTIME }}
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'output/*'
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
